<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>815e8c89-4011-43d7-b629-cb35057756d2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UseCases\Blazorit.UseCases.csproj" />
    <ProjectReference Include="..\Domain\Entities\Blazorit.Domain.Entities.csproj" />
  </ItemGroup>

  <ItemGroup Label="External">
    <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
<!--    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />-->
<!--    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">-->
<!--      <PrivateAssets>all</PrivateAssets>-->
<!--      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--    </PackageReference>-->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />    
  </ItemGroup>

</Project>
