// <auto-generated />
using System;
using Blazorit.Infrastructure.DBStorages.EShop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blazorit.Infrastructure.Migrations.DomDb
{
    [DbContext(typeof(DomDbContext))]
    partial class DomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.CartShopcart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cart_shopcart");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_cart_shopcart_user_id");

                    b.ToTable("cart_shopcart", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.CartShopcartList", b =>
                {
                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("CartId", "ProductId")
                        .HasName("pk_cart_shopcart_list");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cart_shopcart_list_product_id");

                    b.ToTable("cart_shopcart_list", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DeliveryCost")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("delivery_cost");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<DateTimeOffset?>("DeliveryTimeEnd")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_end");

                    b.Property<DateTimeOffset?>("DeliveryTimeStart")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_start");

                    b.Property<long>("UserDeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_delivery_id");

                    b.HasKey("Id")
                        .HasName("pk_dly_delivery");

                    b.HasIndex("UserDeliveryId")
                        .HasDatabaseName("ix_dly_delivery_user_delivery_id");

                    b.ToTable("dly_delivery", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDeliveryAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dly_delivery_address");

                    b.ToTable("dly_delivery_address", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDeliveryMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("EnterAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("enter_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.HasKey("Id")
                        .HasName("pk_dly_delivery_method");

                    b.ToTable("dly_delivery_method", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyMethodsAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<long>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.HasKey("Id")
                        .HasName("pk_dly_methods_address");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_dly_methods_address_address_id");

                    b.HasIndex("MethodId", "AddressId")
                        .IsUnique()
                        .HasDatabaseName("ix_dly_methods_address_method_id_address_id");

                    b.ToTable("dly_methods_address", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyUserDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dly_user_delivery");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_dly_user_delivery_address_id");

                    b.HasIndex("MethodId")
                        .HasDatabaseName("ix_dly_user_delivery_method_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dly_user_delivery_user_id");

                    b.HasIndex("UserId", "MethodId", "AddressId")
                        .IsUnique()
                        .HasDatabaseName("ix_dly_user_delivery_user_id_method_id_address_id");

                    b.ToTable("dly_user_delivery", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdCheckoutOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Canceled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("canceled")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<string>("OrderToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_token");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("payment_amount");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ord_checkout_order");

                    b.HasIndex("OrderToken")
                        .IsUnique()
                        .HasDatabaseName("ix_ord_checkout_order_order_token");

                    b.HasIndex("OrderToken", "Canceled")
                        .IsUnique()
                        .HasDatabaseName("ix_ord_checkout_order_order_token_canceled");

                    b.ToTable("ord_checkout_order", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ord_order");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_ord_order_delivery_id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_ord_order_payment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ord_order_user_id");

                    b.ToTable("ord_order", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdOrderList", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("pk_ord_order_list");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_ord_order_list_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_ord_order_list_product_id");

                    b.ToTable("ord_order_list", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.PmntPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CheckoutOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_order_id");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("OrderToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_token");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("payment_amount");

                    b.Property<string>("PaymentInfo")
                        .HasColumnType("text")
                        .HasColumnName("payment_info");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.HasKey("Id")
                        .HasName("pk_pmnt_payment");

                    b.HasIndex("CheckoutOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_pmnt_payment_checkout_order_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_pmnt_payment_payment_method_id");

                    b.ToTable("pmnt_payment", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.PmntPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsCod")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cod");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("method");

                    b.Property<long>("Ordby")
                        .HasColumnType("bigint")
                        .HasColumnName("ordby");

                    b.HasKey("Id")
                        .HasName("pk_pmnt_payment_method");

                    b.ToTable("pmnt_payment_method", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PrefixSku")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix_sku");

                    b.HasKey("Id")
                        .HasName("pk_prod_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_prod_category_name");

                    b.ToTable("prod_category", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdPicture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LinkPart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("link_part");

                    b.Property<short>("OrderNum")
                        .HasColumnType("smallint")
                        .HasColumnName("order_num");

                    b.Property<string>("PicSize")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pic_size")
                        .HasDefaultValueSql("'medium'::character varying");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site_location")
                        .HasDefaultValueSql("'site'::character varying");

                    b.HasKey("Id")
                        .HasName("pk_prod_picture");

                    b.HasIndex("ProductId", "PicSize", "SiteLocation")
                        .HasDatabaseName("ix_prod_picture_product_id_pic_size_site_location");

                    b.HasIndex("ProductId", "PicSize", "SiteLocation", "OrderNum")
                        .IsUnique()
                        .HasDatabaseName("ix_prod_picture_product_id_pic_size_site_location_order_num");

                    b.ToTable("prod_picture", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Curr")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsOnSite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_site")
                        .HasDefaultValueSql("true");

                    b.Property<string>("LinkPart")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link_part")
                        .HasDefaultValueSql("'empty'::character varying");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_prod_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_prod_product_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_prod_product_sku");

                    b.HasIndex("LinkPart", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_prod_product_link_part_category_id");

                    b.ToTable("prod_product", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwCartShopcart", b =>
                {
                    b.Property<long?>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<DateTime?>("DateTimeItemCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_item_create");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductLinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_link_part");

                    b.Property<decimal?>("ProductPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("product_price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("vw_cart_shopcart", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwDlyDelivery", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<decimal?>("DeliveryCost")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("delivery_cost");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<DateTimeOffset?>("DeliveryTimeEnd")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_end");

                    b.Property<DateTimeOffset?>("DeliveryTimeStart")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_start");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("vw_dly_delivery", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwDlyMethodsAddress", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.ToTable("vw_dly_methods_address", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwDlyUserDelivery", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("vw_dly_user_delivery", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwOrdOrder", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<long?>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("OrderPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("order_price");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductLinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_link_part");

                    b.Property<decimal?>("ProductPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("product_price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("vw_ord_order", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.VwProdProduct", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_full_name");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateOnly?>("DateModified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool?>("IsOnSite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_site");

                    b.Property<string>("LinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link_part");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.ToTable("vw_prod_product", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.WishWish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wish_wish");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wish_wish_user_id");

                    b.ToTable("wish_wish", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.WishWishList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("WishId")
                        .HasColumnType("bigint")
                        .HasColumnName("wish_id");

                    b.HasKey("Id")
                        .HasName("pk_wish_wish_list");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_wish_wish_list_product_id");

                    b.HasIndex("WishId")
                        .HasDatabaseName("ix_wish_wish_list_wish_id");

                    b.ToTable("wish_wish_list", (string)null);
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.CartShopcartList", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.CartShopcart", "Cart")
                        .WithMany("CartShopcartLists")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("fk_cart_shopcart_list_cart_shopcart_cart_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.ProdProduct", "Product")
                        .WithMany("CartShopcartLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_cart_shopcart_list_prod_product_product_id");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDelivery", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyUserDelivery", "UserDelivery")
                        .WithMany("DlyDeliveries")
                        .HasForeignKey("UserDeliveryId")
                        .IsRequired()
                        .HasConstraintName("fk_dly_delivery_dly_user_delivery_user_delivery_id");

                    b.Navigation("UserDelivery");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyMethodsAddress", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyDeliveryAddress", "Address")
                        .WithMany("DlyMethodsAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dly_methods_address_dly_delivery_address_address_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyDeliveryMethod", "Method")
                        .WithMany("DlyMethodsAddresses")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dly_methods_address_dly_delivery_method_method_id");

                    b.Navigation("Address");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyUserDelivery", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyDeliveryAddress", "Address")
                        .WithMany("DlyUserDeliveries")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dly_user_delivery_dly_delivery_address_address_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyDeliveryMethod", "Method")
                        .WithMany("DlyUserDeliveries")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dly_user_delivery_dly_delivery_method_method_id");

                    b.Navigation("Address");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdOrder", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.DlyDelivery", "Delivery")
                        .WithOne("OrdOrder")
                        .HasForeignKey("Blazorit.Domain.EShop.EF.dom.OrdOrder", "DeliveryId")
                        .IsRequired()
                        .HasConstraintName("fk_ord_order_dly_delivery_delivery_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.PmntPayment", "Payment")
                        .WithOne("OrdOrder")
                        .HasForeignKey("Blazorit.Domain.EShop.EF.dom.OrdOrder", "PaymentId")
                        .IsRequired()
                        .HasConstraintName("fk_ord_order_pmnt_payment_payment_id");

                    b.Navigation("Delivery");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdOrderList", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.OrdOrder", "Order")
                        .WithMany("OrdOrderLists")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_ord_order_list_ord_order_order_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.ProdProduct", "Product")
                        .WithMany("OrdOrderLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_ord_order_list_prod_product_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.PmntPayment", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.PmntPaymentMethod", "PaymentMethod")
                        .WithMany("PmntPayments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("fk_pmnt_payment_pmnt_payment_method_payment_method_id");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdPicture", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.ProdProduct", "Product")
                        .WithMany("ProdPictures")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_prod_picture_prod_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdProduct", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.ProdCategory", "Category")
                        .WithMany("ProdProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prod_product_prod_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.WishWishList", b =>
                {
                    b.HasOne("Blazorit.Domain.EShop.EF.dom.ProdProduct", "Product")
                        .WithMany("WishWishLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_wish_wish_list_prod_product_product_id");

                    b.HasOne("Blazorit.Domain.EShop.EF.dom.WishWish", "Wish")
                        .WithMany("WishWishLists")
                        .HasForeignKey("WishId")
                        .IsRequired()
                        .HasConstraintName("fk_wish_wish_list_wish_wish_wish_id");

                    b.Navigation("Product");

                    b.Navigation("Wish");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.CartShopcart", b =>
                {
                    b.Navigation("CartShopcartLists");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDelivery", b =>
                {
                    b.Navigation("OrdOrder");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDeliveryAddress", b =>
                {
                    b.Navigation("DlyMethodsAddresses");

                    b.Navigation("DlyUserDeliveries");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyDeliveryMethod", b =>
                {
                    b.Navigation("DlyMethodsAddresses");

                    b.Navigation("DlyUserDeliveries");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.DlyUserDelivery", b =>
                {
                    b.Navigation("DlyDeliveries");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.OrdOrder", b =>
                {
                    b.Navigation("OrdOrderLists");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.PmntPayment", b =>
                {
                    b.Navigation("OrdOrder");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.PmntPaymentMethod", b =>
                {
                    b.Navigation("PmntPayments");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdCategory", b =>
                {
                    b.Navigation("ProdProducts");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.ProdProduct", b =>
                {
                    b.Navigation("CartShopcartLists");

                    b.Navigation("OrdOrderLists");

                    b.Navigation("ProdPictures");

                    b.Navigation("WishWishLists");
                });

            modelBuilder.Entity("Blazorit.Domain.EShop.EF.dom.WishWish", b =>
                {
                    b.Navigation("WishWishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
