// <auto-generated />
using System;
using Blazorit.Infrastructure.DBStorages.EShop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blazorit.Infrastructure.Migrations
{
    [DbContext(typeof(DomDbContext))]
    partial class BlazoritContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.CartShopcart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("cart_shopcarts_pkey");

                    b.HasIndex(new[] { "UserId" }, "UQIX__cart_shopcarts__user_id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "fki_fk__cart_shop_carts__ident_users");

                    b.ToTable("cart_shopcarts", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.CartShopcartList", b =>
                {
                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("CartId", "ProductId")
                        .HasName("cart_shopcart_lists_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_shopcart_lists", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DeliveryCost")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("delivery_cost");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<DateTimeOffset?>("DeliveryTimeEnd")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_end");

                    b.Property<DateTimeOffset?>("DeliveryTimeStart")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_start");

                    b.Property<long>("UserDeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_delivery_id");

                    b.HasKey("Id")
                        .HasName("dly_deliveries_pkey");

                    b.HasIndex("UserDeliveryId");

                    b.ToTable("dly_deliveries", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("dly_delivery_address_pkey");

                    b.ToTable("dly_delivery_addresses", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("EnterAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("enter_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.HasKey("Id")
                        .HasName("dly_delivery_methods_pkey");

                    b.ToTable("dly_delivery_methods", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyMethodsAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<long>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.HasKey("Id")
                        .HasName("dly_methods_addresses_pkey");

                    b.HasIndex(new[] { "MethodId", "AddressId" }, "UK__dly_methods_addresses")
                        .IsUnique();

                    b.HasIndex(new[] { "AddressId" }, "fki_FK__dly_methods_addresses__dly_delivery_addresses");

                    b.ToTable("dly_methods_addresses", "dom", t =>
                        {
                            t.HasComment("The table is for shipping methods where the address offered by the system is common to all users");
                        });
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyUserDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("dly_user_deliveries_pkey");

                    b.HasIndex(new[] { "UserId", "MethodId", "AddressId" }, "UQ__dly_user_deliveries")
                        .IsUnique();

                    b.HasIndex(new[] { "AddressId" }, "fki_FK__dly_user_deliveries__dly_delivery_addresses");

                    b.HasIndex(new[] { "MethodId" }, "fki_FK__dly_user_deliveries__dly_delivery_methods");

                    b.HasIndex(new[] { "UserId" }, "fki_FK__dly_user_deliveries__ident_users");

                    b.ToTable("dly_user_deliveries", "dom", t =>
                        {
                            t.HasComment("Addresses entered by the users");
                        });
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdCheckoutOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Canceled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("canceled")
                        .HasDefaultValueSql("true")
                        .HasComment("if this field is canceled, than you can delete this row from table.");

                    b.Property<DateTime>("DateTimeCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<string>("OrderToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_token")
                        .HasComment("uniq token");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("payment_amount");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ord_checkout_orders_pkey");

                    b.HasIndex(new[] { "OrderToken" }, "UQ__ord_checkout_orders__order_token")
                        .IsUnique();

                    b.HasIndex(new[] { "OrderToken", "Canceled" }, "uqix__ord_checkout_orders__order_token__canceled")
                        .IsUnique();

                    b.ToTable("ord_checkout_orders", "dom", t =>
                        {
                            t.HasComment("this table need for temporary storage info about order, while payment is being made");
                        });
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ord_orders_pkey");

                    b.HasIndex(new[] { "DeliveryId" }, "UQ__ord_orders__delivery_id")
                        .IsUnique();

                    b.HasIndex(new[] { "PaymentId" }, "UQ__ord_orders__payment_id")
                        .IsUnique();

                    b.HasIndex(new[] { "DeliveryId" }, "fki_fk__ord_orders__dly_deliveries");

                    b.HasIndex(new[] { "DeliveryId" }, "fki_fk__ord_orders__dly_user_deliveries");

                    b.HasIndex(new[] { "PaymentId" }, "fki_fk__ord_orders__pmnt_payments");

                    b.HasIndex(new[] { "UserId" }, "fki_fk__ord_orders__users__id");

                    b.ToTable("ord_orders", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrderList", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("ord_order_list_pkey");

                    b.HasIndex(new[] { "OrderId" }, "fki_fk__ord_order_list__ord_order");

                    b.HasIndex(new[] { "ProductId" }, "fki_fk__ord_order_list__prod_products");

                    b.ToTable("ord_order_lists", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CheckoutOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_order_id")
                        .HasComment("this field relation to id of ord_checkout_orders, but rows in ord_checkout_orders table can be deleted (whose canceled), than we have not Foreign key to ord_checkout_orders");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("OrderToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_token");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("payment_amount");

                    b.Property<string>("PaymentInfo")
                        .HasColumnType("text")
                        .HasColumnName("payment_info");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.HasKey("Id")
                        .HasName("pmnt_payments_pkey");

                    b.HasIndex(new[] { "CheckoutOrderId" }, "UQ__checkout_order_id")
                        .IsUnique();

                    b.HasIndex(new[] { "PaymentMethodId" }, "fki_fk__pmnt_payments__pmnt_payment_methods");

                    b.HasIndex(new[] { "CheckoutOrderId" }, "fki_fk_not_valid__pmnt_payments__checout_orders__id");

                    b.ToTable("pmnt_payments", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsCod")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cod")
                        .HasComment("Is Cash On Delivery");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("method");

                    b.Property<long>("Ordby")
                        .HasColumnType("bigint")
                        .HasColumnName("ordby");

                    b.HasKey("Id")
                        .HasName("pmnt_payment_methods_pkey");

                    b.ToTable("pmnt_payment_methods", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), null, null, 0L, null, null, null);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PrefixSku")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix_sku");

                    b.HasKey("Id")
                        .HasName("prod_categories_pkey");

                    b.HasIndex(new[] { "Name" }, "UQIX__prod_categories__name")
                        .IsUnique();

                    b.ToTable("prod_categories", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdPicture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("LinkPart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("link_part");

                    b.Property<short>("OrderNum")
                        .HasColumnType("smallint")
                        .HasColumnName("order_num");

                    b.Property<string>("PicSize")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pic_size")
                        .HasDefaultValueSql("'medium'::character varying");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site_location")
                        .HasDefaultValueSql("'site'::character varying");

                    b.HasKey("Id")
                        .HasName("prod_pictures_pkey");

                    b.HasIndex(new[] { "ProductId", "PicSize", "SiteLocation" }, "IX__prod_pictures__include");

                    b.HasIndex(new[] { "ProductId", "PicSize", "SiteLocation", "OrderNum" }, "UQ__prod_pictures")
                        .IsUnique();

                    b.ToTable("prod_pictures", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Curr")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateTimeModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsOnSite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_site")
                        .HasDefaultValueSql("true")
                        .HasComment("if on_site is true than this product show on the site, else not show");

                    b.Property<string>("LinkPart")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link_part")
                        .HasDefaultValueSql("'empty'::character varying");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku")
                        .HasComment("articul");

                    b.HasKey("Id")
                        .HasName("prod_products_pkey");

                    b.HasIndex(new[] { "LinkPart", "CategoryId" }, "UQIX__prod_products__include")
                        .IsUnique();

                    b.HasIndex(new[] { "Sku" }, "UQIX__prod_products__sku")
                        .IsUnique();

                    b.HasIndex(new[] { "CategoryId" }, "fki_fk__prod_products__prod_categories");

                    b.ToTable("prod_products", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwCartShopcart", b =>
                {
                    b.Property<long?>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<DateTime?>("DateTimeItemCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_item_create");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductLinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_link_part");

                    b.Property<decimal?>("ProductPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("product_price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_cart_shopcarts", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwDlyDelivery", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<decimal?>("DeliveryCost")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("delivery_cost");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<DateTimeOffset?>("DeliveryTimeEnd")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_end");

                    b.Property<DateTimeOffset?>("DeliveryTimeStart")
                        .HasColumnType("time with time zone")
                        .HasColumnName("delivery_time_start");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_dly_deliveries", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwDlyMethodsAddress", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("MethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("method_id");

                    b.ToTable((string)null);

                    b.ToView("vw_dly_methods_addresses", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwDlyUserDelivery", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_created");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_dly_user_deliveries", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwOrdOrder", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<long?>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("OrderPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("order_price");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductLinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_link_part");

                    b.Property<decimal?>("ProductPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("product_price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_ord_orders", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.VwProdProduct", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_full_name");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("curr");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<DateOnly?>("DateModified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create");

                    b.Property<DateTime?>("DateTimeModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool?>("IsOnSite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_site");

                    b.Property<string>("LinkPart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link_part");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.ToTable((string)null);

                    b.ToView("vw_prod_products", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.WishWish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("wish_wishes_pkey");

                    b.HasIndex(new[] { "UserId" }, "UQIX__wish_wishes__user_id")
                        .IsUnique();

                    b.ToTable("wish_wishes", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.WishWishList", b =>
                {
                    b.Property<long>("WishId")
                        .HasColumnType("bigint")
                        .HasColumnName("wish_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_create")
                        .HasDefaultValueSql("now()");

                    b.HasKey("WishId", "ProductId")
                        .HasName("wish_wish_lists_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("wish_wish_lists", "dom");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.ident.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", "ident");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.CartShopcartList", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.CartShopcart", "Cart")
                        .WithMany("CartShopcartLists")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("fk__cart_shopcart_lists__cart_shopcart");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", "Product")
                        .WithMany("CartShopcartLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk__cart_shopcart_lists__prod_products");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDelivery", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyUserDelivery", "UserDelivery")
                        .WithMany("DlyDeliveries")
                        .HasForeignKey("UserDeliveryId")
                        .IsRequired()
                        .HasConstraintName("fki_fk__dly_deliveries__dly_user_deliveries");

                    b.Navigation("UserDelivery");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyMethodsAddress", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryAddress", "Address")
                        .WithMany("DlyMethodsAddresses")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK__dly_methods_addresses__dly_delivery_addresses");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryMethod", "Method")
                        .WithMany("DlyMethodsAddresses")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__dly_methods_addresses__dly_delivery_methods");

                    b.Navigation("Address");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyUserDelivery", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryAddress", "Address")
                        .WithMany("DlyUserDeliveries")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK__dly_user_deliveries__dly_delivery_addresses");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryMethod", "Method")
                        .WithMany("DlyUserDeliveries")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__dly_user_deliveries__dly_delivery_methods");

                    b.Navigation("Address");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDelivery", "Delivery")
                        .WithOne("OrdOrder")
                        .HasForeignKey("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", "DeliveryId")
                        .IsRequired()
                        .HasConstraintName("fk__ord_orders__dly_deliveries");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPayment", "Payment")
                        .WithOne("OrdOrder")
                        .HasForeignKey("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", "PaymentId")
                        .IsRequired()
                        .HasConstraintName("fk__ord_orders__pmnt_payments");

                    b.Navigation("Delivery");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrderList", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", "Order")
                        .WithMany("OrdOrderLists")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk__ord_order_list__ord_order");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", "Product")
                        .WithMany("OrdOrderLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk__ord_order_list__prod_products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPayment", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPaymentMethod", "PaymentMethod")
                        .WithMany("PmntPayments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("fk__pmnt_payments__pmnt_payment_methods");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdPicture", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", "Product")
                        .WithMany("ProdPictures")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk__prod_pictures__prod_products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdCategory", "Category")
                        .WithMany("ProdProducts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk__prod_products__prod_categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.WishWishList", b =>
                {
                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", "Product")
                        .WithMany("WishWishLists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk__wish_wish_lists__prod_products");

                    b.HasOne("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.WishWish", "Wish")
                        .WithMany("WishWishLists")
                        .HasForeignKey("WishId")
                        .IsRequired()
                        .HasConstraintName("fk__wish_wish_lists__wish_wishes");

                    b.Navigation("Product");

                    b.Navigation("Wish");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.CartShopcart", b =>
                {
                    b.Navigation("CartShopcartLists");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDelivery", b =>
                {
                    b.Navigation("OrdOrder");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryAddress", b =>
                {
                    b.Navigation("DlyMethodsAddresses");

                    b.Navigation("DlyUserDeliveries");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyDeliveryMethod", b =>
                {
                    b.Navigation("DlyMethodsAddresses");

                    b.Navigation("DlyUserDeliveries");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.DlyUserDelivery", b =>
                {
                    b.Navigation("DlyDeliveries");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.OrdOrder", b =>
                {
                    b.Navigation("OrdOrderLists");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPayment", b =>
                {
                    b.Navigation("OrdOrder");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.PmntPaymentMethod", b =>
                {
                    b.Navigation("PmntPayments");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdCategory", b =>
                {
                    b.Navigation("ProdProducts");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.ProdProduct", b =>
                {
                    b.Navigation("CartShopcartLists");

                    b.Navigation("OrdOrderLists");

                    b.Navigation("ProdPictures");

                    b.Navigation("WishWishLists");
                });

            modelBuilder.Entity("Blazorit.Infrastructure.DBStorages.BlazoritDB.EF.dom.WishWish", b =>
                {
                    b.Navigation("WishWishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
