<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\SharedKernel\Blazorit.Domain.SharedKernel.csproj" />
        <ProjectReference Include="..\Domain\Entities\Blazorit.Domain.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Core\" />
    </ItemGroup>

</Project>
